version: '3'
services:
  api:
    build: .
    command: './bin/wait-for-it.sh db:5432 -- yarn dev'
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
    links:
      - db
    depends_on:
      - db

  db:
    image: 'postgres:10.2'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'serverapp'
    volumes:
      - './data:/var/lib/postgresql'
